## <문제>
## 아래 문제를 해결하여 "numpy_성명.ipynb" 파일에 저장하여 제출하세요.


1) datamining4_numpy.ipynb 를 학습하면서 이해안되는 부분에 대한 질문 3개이상 마크다운으로 만들기

2) datamining4_numpy.ipynb 안에 제공되는 실습문제 1, 2, 3을 해결하기

### 빅데이터전공 20175327 이연희

## 실습문제 #1.  1차원 배열 생성, indexing, slicing, assign, operation 연습

### (1) 1~25 사이의 2의 배수 12개로 1차원 배열(a) 생성, 출력

In [103]:
import numpy as np

a=np.arange(2,25,2)
print("a =",a)

a = [ 2  4  6  8 10 12 14 16 18 20 22 24]


### (2) a의 인덱스 2~5의 요소값을 -20으로 수정, 출력

In [105]:
a[2:5] = -20
print("a =",a)

a = [  2   4 -20 -20 -20  12  14  16  18  20  22  24]


### (3) a의 끝에서 두번째부터 끝가지 요소값을 2배하여 저장, 출력 

In [123]:
aa=a[-2:]*2

print("aa =",aa)

aa = [44 48]


### (4) 1~9사이 임의값 12개로  배열 b 생성, 출력

In [112]:
b=np.random.randint(10, size=12)
print("b =",b)

b = [4 5 0 6 3 5 7 3 8 5 3 9]


### (5) b배열을 10배하여 c에 저장

In [113]:
c=b*10
print("c =",c)

c = [40 50  0 60 30 50 70 30 80 50 30 90]


### (6) a배열과 b배열을 더하여 d 배열 생성

In [114]:
d=a+b
print("d =",d)

d = [  6   9 -20 -14 -17  17  21  19  26  25  25  33]


### (7) b배열의 최대,최소,평균 출력

In [117]:
print("max = ", max(b))
print("min = ", min(b))
print("mean = ", b.mean())

max =  9
min =  0
mean =  4.833333333333333


### (8) a에서 b배열의 평균보다 큰값을 추출 

In [135]:
print(a)

[  2   4 -20 -20 -20  12  14  16  18  20  22  24]


In [134]:
print(a[a>b.mean()])

[12 14 16 18 20 22 24]


## 실습문제 #2. 2차원 배열 생성, reshape, resize, 연산 연습

### (1) 1~25 사이의 2의 배수 12개로 1차원 배열(a) 생성, 출력

In [75]:
import numpy as np

a=np.arange(2,25,2)
print("a =",a)

a = [ 2  4  6  8 10 12 14 16 18 20 22 24]


### (2) a를 이용하여  3X4 배열로 변경하여 b생성, 출력

In [76]:
b = a.reshape(3,4)
print("b =\n",b)

b =
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


### (3) a를  2X6 배열로 변경, 출력

In [77]:
a = a.reshape(2,6)
print("c =\n",a)

c =
 [[ 2  4  6  8 10 12]
 [14 16 18 20 22 24]]


### (4) a를  1행의 모든 값을  추출하여 a1을 만들고, a1의 모든 값을 0으로 변경, a1,a출력

In [78]:
a1 = a[0]
print("a1 =",a1)
a1[...] = 0
print("a1 =",a1)

a1 = [ 2  4  6  8 10 12]
a1 = [0 0 0 0 0 0]


### (5) 1~10 사이의 임의의 값으로 3X3 배열 x, y생성, 출력

In [79]:
x = np.round(10*(np.random.random((3,3))))
y = np.round(10*(np.random.random((3,3))))
print("x = \n",x,"\ny = \n",y)

x = 
 [[2. 6. 3.]
 [4. 7. 1.]
 [9. 2. 6.]] 
y = 
 [[ 9.  1.  4.]
 [10.  1.  4.]
 [ 3.  8.  8.]]


### (6) x의 1, 2 행의 모든 열추출, 출력

In [80]:
print("x의 1행 : ",x[1])
print("x의 2행 : ",x[2])

x의 1행 :  [4. 7. 1.]
x의 2행 :  [9. 2. 6.]


### (7) x의 2열의 모든 행 추출, 출력

In [81]:
print("x의 2열 : ",x[:,2])

x의 2열 :  [3. 1. 6.]


### (8) x의 0,2열의 1,2 행 추출, 출력

In [82]:
print("x의 0,2열의 1,2행 추출 : ",x[1:,0])

x의 0,2열의 1,2행 추출 :  [4. 9.]


### (9) x의 각행의 합, 각 열의 합, 출력

In [83]:
print("x의 각 행의 합")
print("0 행 : ",np.sum(x[0]))
print("1 행 : ",np.sum(x[1]))
print("2 행 : ",np.sum(x[2]))

x의 각 행의 합
0 행 :  11.0
1 행 :  12.0
2 행 :  17.0


In [84]:
print("x의 각 열의 합")
print("0 열 : ",np.sum(x[:,0]))
print("1 열 : ",np.sum(x[:,1]))
print("2 열 : ",np.sum(x[:,2]))

x의 각 열의 합
0 열 :  15.0
1 열 :  15.0
2 열 :  10.0


### (10) x의 각행의 최대, 각 열의 최대, 출력

In [85]:
print("x의 각행의 최대값, 각 열의 최대값, 출력")
print("0 행 : ",np.max(x[0]))
print("1 행 : ",np.max(x[1]))
print("2 행 : ",np.max(x[2]))
print("0 열 : ",np.max(x[:,0]))
print("1 열 : ",np.max(x[:,1]))
print("2 열 : ",np.max(x[:,2]))

x의 각행의 최대값, 각 열의 최대값, 출력
0 행 :  6.0
1 행 :  7.0
2 행 :  9.0
0 열 :  9.0
1 열 :  7.0
2 열 :  6.0


### (11) x와 y의 합 결과 출력

In [86]:
mat_sum = x + y
mat_mul = x * y
mat_inner = np.matmul(x,y)

print("합 : \n",mat_sum)

합 : 
 [[11.  7.  7.]
 [14.  8.  5.]
 [12. 10. 14.]]


### (12) X를 1차원으로 변경하여 x1 생성

In [130]:
print(x)

x1 =x.ravel()
for e in x1:
    print(e, end=" ")

[[2. 6. 3.]
 [4. 7. 1.]
 [9. 2. 6.]]
2.0 6.0 3.0 4.0 7.0 1.0 9.0 2.0 6.0 

## 실습문제 # 3. 배열복사, 결합 연습

### (1) 1-3, 10-30, 100-300 3개의 1차원 배열(a1,a2,a3)을 생성하여 행으로 결합된 y배열 생성

In [98]:
a1 = np.arange(1,4)
a2 = np.arange(10,40,10)
a3 = np.arange(100,400,100)

y = np.vstack([a1,a2,a3])
print(y)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


### (2) y배열의 0,2 열을 복사하여 y1, 1열을 복사하여 y2 생성

In [100]:
y1 = np.vstack([y[:,0],y[:,2]])
y1 = y1.T
print("Y1:\n",y1)

y2 = y[:,1].reshape(3,1)
print("\nY2:\n",y2)

Y1:
 [[  1   3]
 [ 10  30]
 [100 300]]

Y2:
 [[  2]
 [ 20]
 [200]]


### (3) y1, y2를 결합하여 yy배열 생성

In [101]:
yy = np.vstack([y1.T,y2.T])
yy = yy.T
print("YY:\n",yy)

YY:
 [[  1   3   2]
 [ 10  30  20]
 [100 300 200]]
